version: '3.7'

services:

  api-gateway:
    image: gateway
    build: ./Tarefa1_SistemaDeVendas/ApiGatewayServico
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  estoque:
    image: estoque
    build: ./Tarefa1_SistemaDeVendas/EstoqueServico
    mem_limit: 700m
    ports:
      - "8200:8200"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  naming-server:
    image: nameserver
    build: ./Tarefa1_SistemaDeVendas/NamingServerServico
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

  nota-servico:
    image: nota
    build: ./Tarefa1_SistemaDeVendas/NotaFiscalServico
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  venda:
    image: venda
    build: ./Tarefa1_SistemaDeVendas/VendaServico
    mem_limit: 700m
    ports:
      - 8080:8080
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      restart: always #Restart if there is a problem starting up

  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    depends_on:
      - rabbitmq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    restart: always #Restart if there is a problem starting up


  rabbitmq:
    image: rabbitmq:3.8.12-management
    mem_limit: 300m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - currency-network

networks:
  currency-network: